### ISSUE TITLE
Incorrect return type of the `chooseFolder` method

### ISSUE THREAD

**Issue by Artawower** [zagham-nadeem/capacitor-folder-picker#1]
Readme says:

```
Returns: Promise<{ path: string }> - A promise that resolves with the selected folder path.
```

And it looks like a real return value, but the type definition says that key is a `value`, not a `path`

![image](https://github.com/user-attachments/assets/6769b66b-dee3-448d-9157-bf5fb292e7b4)

https://github.com/zagham-nadeem/capacitor-folder-picker/blob/main/src/definitions.ts

Shouldn't it be `{ path: string }`?

**Comment by zagham-nadeem** [comment]
Hey @Artawower thanks for the issue
I fix this today

**Comment by rodrgds** [comment]
> Hey @Artawower thanks for the issue I fix this today

Will you? 😅

**Comment by zagham-nadeem** [comment]
hey @Artawower i was too busy these days with my clients sorry for all the inconvenience but i fix this

**Comment by zagham-nadeem** [comment]
i. have changed path to value in readme @Artawower
